// File generated by FlutterFire CLI.
// This is a placeholder. Run the following commands to configure:
//
// 1. firebase login
// 2. flutterfire configure
//
// This will auto-generate the real firebase_options.dart file.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return android;
      case TargetPlatform.linux:
        return android;
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── REPLACE THESE WITH YOUR FIREBASE PROJECT VALUES ──
  // Run: firebase login && flutterfire configure

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
    storageBucket: 'YOUR_PROJECT_ID.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFS4uakZ0dY8VrKpTF0HjOkOFpkt9ikkk',
    appId: '1:250113192669:android:8b9a875a21a60f2301a134',
    messagingSenderId: '250113192669',
    projectId: 'avishu-superappp',
    storageBucket: 'avishu-superappp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_bjysGkWIE35UJBuyvKOsJS-JStoUCpg',
    appId: '1:250113192669:ios:19607f29de02e24c01a134',
    messagingSenderId: '250113192669',
    projectId: 'avishu-superappp',
    storageBucket: 'avishu-superappp.firebasestorage.app',
    iosBundleId: 'com.example.fashionmodeHackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.firebasestorage.app',
    iosBundleId: 'com.example.fashionmodeHackathon',
  );
}